### ISSUE TITLE
ApiHeaders keeps adding job arguments

### ISSUE THREAD

**Issue by benthorner** [alphagov/govuk_sidekiq#37]
The ApiHeaders middleware currently adds a hash consisting of `authenticated_user` and `request_id`, as the last job argument when a job is scheduled on Sidekiq.

However, this argument is also added again each time the job is retried, which means we have to write our worker perform method as `def perform(our_arg, *_govuk_sidekiq_args)`.

Could we change this so that the middleware checks if the hash is already present before injecting it again?

**Comment by tijmenb** [comment]
Yeah, that seems like a good idea. I'm confused why we haven't seen this behaviour before, where did you run into this?

**Comment by benthorner** [comment]
We're putting GOV.UK Sidekiq into datagovuk_publish at the moment and we've got a few failing jobs we were looking at. We're a bit tied up at the moment, otherwise I would have made a PR :-)

**Comment by benthorner** [comment]
It looks like the ServerMiddleware is running just fine. What I suspect is happening is that somehow the args the ClientMiddleware sees are for the original job and not the copy modified by the server when it tried to run it. Think I've found the problem - line 119 :-|

https://github.com/mperham/sidekiq/blob/822a75db12befdedaf66980a2394c62dbf9c3322/lib/sidekiq/processor.rb
